name: "send-test-to-pull-request"
description: "This is a example code."
branding:
    icon: "activity"
    color: "blue"
inputs:
    github-token:
        description: "token of github"
        required: true
runs:
    using: "composite"
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch to base branch
        shell: bash
        run: git fetch origin ${{ github.event.pull_request.base.sha }}:BASE

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.8"
            architecture: "x64"

      - name: Clone Python Script
        shell: bash
        run: |
            git clone https://github.com/TaikiHoshika/ActionTest.git
            echo "$(ls -la)"

      - name: Run Python Script
        shell: bash
        env:
            GITHUB_TOKEN: ${{ github.event.inputs.github-token }}
            URL: ${{ github.event.pull_request.html_url }}
        run: |
            cd ActionTest
            response=$(python dist/main.py)
            echo "${response}" > body.txt
            gh pr comment --body-file body.txt "${URL}"