name: TestAction

on:
    pull_request:
        types: [opened, reopened]

jobs:
    TestJob:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
          - name: Checkout pull request branch
            uses: actions/checkout@v3
            with:
                ref: ${{ github.event.pull_request.head.sha }}
          - name: Fetch to base branch
            run: git fetch origin ${{ github.event.pull_request.base.sha }}:BASE

          - name: Setup Python
            uses: actions/setup-python@v3
            with:
                python-version: "3.8"
                architecture: "x64"

          - name: Run Python Script
            shell: bash
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                URL: ${{ github.event.pull_request.html_url }}
            run: |
                response=$(python .github/workflows/main.py)
                echo "${response}" > body.txt
                gh pr comment --body-file body.txt "${URL}"